### ISSUE TITLE
add_sbtab_string() missing 1 required positional argument: 'filename'

### ISSUE THREAD

**Issue by Anha101** [tlubitz/SBtab#111]
Hello everyone!
Someone please tell me what the error is?( 
I have been sitting for 3 days, but I could not figure it out(
![Снимок экрана (30)](https://user-images.githubusercontent.com/78921922/107990296-bb55a900-7006-11eb-8654-31171333b8d9.png)

**Comment by tlubitz** [comment]
Hi Anha,

no problem, let's figure this out. You have created an SBtab Document and you want to add an SBtab file in form of a string. For this, you will need to provide two parameters: the file_content as a string (like you already do), and a filename as a string. So everything should be good to go if you write

`Sd.add_sbtab_string(file_content, filename="blabla.tsv")`

That should do the trick. I assume that you might have been confused because there are 2 functions in SBtab.py which are called "add_sbtab_string()". The first one is for the class SBtabTable and does not require a parameter "filename". But the second function is that of the class SBtabDocument, which you are using. And that one DOES require the parameter filename, because the files within a Document may be multiple and need to be distinguished from one another, while SBtabTable can only hold one single file.

I hope this helps
